### ISSUE TITLE
Kodi 19

### ISSUE THREAD

**Issue by trkselim** [denimnani/service.subloader#10]
Any plans for kodi 19
It’s  grate addon I hope you can make it work with kodi 19
Happy new year ☺️

**Comment by denimnani** [comment]
Happy new year ;)
I will start working on that next month.
A new update should be coming very soon.

**Comment by FantasieGamer** [comment]
Also looking forward to the python 3 update for this addon, only way that I know of to use my own subtitles.org-account while auto downloading the matching subs.

**Comment by peno64** [comment]
I already have a first working version for kodi 19.  @denimnani if you are interested, let me know.

**Comment by denimnani** [comment]
> I already have a first working version for kodi 19. @denimnani if you are interested, let me know.

That's really awesome, I was starting to do it next weekend. I will contact you next week ;)

**Comment by peno64** [comment]
@denimnani Great. For what I can see it works 100% now on both kodi 18 and 19 (the same sources). So give me a yell and I will send it to you.

**Comment by FantasieGamer** [comment]
If you guys need a beta tester. Sign me up!
@peno64 @denimnani

**Comment by trkselim** [comment]
Can you shared the files?

**Comment by peno64** [comment]
Ok, just a moment, I will put it on github and share it with you

**Comment by peno64** [comment]
@trkselim You should now have access to my subloader repo. Note that I changed it as such that it works for kodi 18 and 19

**Comment by peno64** [comment]
@denimnani I also shared my subloader repo for you

**Comment by denimnani** [comment]
Hi @peno64 , just ended the update on Subloader 0.1.5, thank so much for your support, you made my life way easier 😊.
If possible, go to my repo and do a fork, is the best practice for this cases, like that you will be able to send me pull request’s directly, if you don’t know what I’m talking about go check on Youtube “Github-Creating Forks and Pull Requests” there are plenty of videos showing how to do it. For future collaboration this is the way to go.
@FantasieGamer  I’m thinking in create a new branch for ongoing work that needs to be tested.
Not sure yet when I’m going to post it, but will do it as soon I get a bit more time.
I also have started a discussion tab over here, should be easier to talk directly with any of you, just look at “Discussions” in the menu.

Thanks again @peno64
