### ISSUE TITLE
Not a issue, i translated to Dutch for you

### ISSUE THREAD

**Issue by Tinuz97** [denimnani/service.subloader#2]
Hi, i just translated the addon to Dutch language (seperate Folder named Dutch, and the strings.po also Dutch).

Tested,working 100%.

No idea how i can send it to you :)

**Comment by Tinuz97** [comment]
You need to rename it to strings.po 
[strings.txt](https://github.com/denimnani/service.subloader/files/3422505/strings.txt)

**Comment by denimnani** [comment]
The best way to do it is to issue a pull request with the new files.
If your unable to do it like that just use the web share "https://gofile.io/" and send me the link and i will do it.

**Comment by Tinuz97** [comment]
I am pretty new to this GitHub thing :) 

Renaming the strings.txt (PO not allowed in this chat) to strings.po does the job also for now. 

I am gonna take a look on how the other functions on github work :)

**Comment by Tinuz97** [comment]
Here is the file https://gofile.io/?c=3oNhQv

You only need to create a folder named Dutch, and put it in that location (pretty sure you know that, just in case)

**Comment by denimnani** [comment]
Just done...
Thanks :)

**Comment by Tinuz97** [comment]
No problem, i got bored, because it is hot in the netherlands.

Thank you for this great addon :)

**Comment by Tinuz97** [comment]
I think you need to make it 0.1.4 ,otherwise people who already updated don't get the update pushed :)

**Comment by denimnani** [comment]
Yes i will do it but it takes some time and i'm at work.
Later today i will push an official update for this

**Comment by denimnani** [comment]
Done...
Thanks again for your contribution
