### ISSUE TITLE
Kodi hangs on 0.1.4 (freeze)

### ISSUE THREAD

**Issue by Tinuz97** [denimnani/service.subloader#3]
I have a wierd issue with 0.1.4.
It does work fine (the sub loads ), but if i choose manually a subtitle in kodi, and i hit the download subtitle button, kodi freezes.

It is not possible to log it (with ctrl-shift-d) because the freeze is so hard it can not write a log.
I have this issue on my nvidia shield,computer and my phone.
If i remove 0.1.4, and install 0.1.3 i do not have this freezing issue.

Sorry i can not give any log details, because it is nnot possible because of the freezing.

**Comment by denimnani** [comment]
I will look into it, but if you could set the debug option in subloader, and manually go to kodi folder and upload the log.

**Comment by Tinuz97** [comment]
I will try that, to see if it can write a log.
Because with advanced logging with kodi is not possible (the freeze is so fast, that advanced logging is not able to write the log).

**Comment by Tinuz97** [comment]
This is weird,now it does noy hang/freeze like yesterday.
What makes me wonder,could it hang/freeze if opensubtitles website has issues mayeby?
Now it is working fine (yesterday it did freeze kodi everytime on all my devices).

**Comment by denimnani** [comment]
That is weird, i will let the issue open for now, if your able to replicate it again let me know.

**Comment by Tinuz97** [comment]
I keep a eye on it, thx.

**Comment by denimnani** [comment]
@Tinuz97 tell me one thing during yesterday have you try to set the login in Subloader settings, and if so, have you get any error message?

**Comment by Tinuz97** [comment]
I do not have set the login option, I have those fields clean 👍

**Comment by denimnani** [comment]
Not subloader related
