### ISSUE TITLE
Subscene provider not working

### ISSUE THREAD

**Issue by hejman** [denimnani/service.subloader#4]
Hi, subscene provider always returns no results for me, while opensubtitles works fine.
I have validated the search using the website and something is off.

I am using a streaming addon with danish 1st, then english 2nd language.

Could it be because the IMDB-id is used? (if i search subscene for an imdb id I get no results)

**Comment by hejman** [comment]
Subscene provider issue.

**Comment by peno64** [comment]
See https://howtomediacenter.com/en/tutorial-how-to-enable-automatic-subtitles-on-kodi/ for a solution. There is a newer version of the subscene subtitle addon mentioned there which does work
